### ISSUE TITLE
HDMI外接显示器无显示

### ISSUE THREAD

**Issue by CalvinNg-git** [LnZh21/Hackintosh-fx50vx6300#2]
HDMI输出不了😂

**Comment by CalvinNg-git** [comment]
大佬求解呀。HDMI外接显示器无信号。只能用笔记本的显示器

**Comment by CalvinNg-git** [comment]
是不是你把现存改了的原因啊😂，要怎么改回去。

**Comment by AikenZh** [comment]
抱歉哈，我目前没有用到过hdmi，也没有设备测试，显存我是用hackintool改的

**Comment by AikenZh** [comment]
https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html
试试看这篇文章能不能帮到你

**Comment by CalvinNg-git** [comment]
我都是拿现成的，完全不会改啊😂。只能等大佬您更新了。伸手党的悲哀。

**Comment by CalvinNg-git** [comment]
我用hackintool折腾了几天都没有效果😂。

**Comment by CalvinNg-git** [comment]
伙计们我弄好了，要用HDMI输出显示器的老哥们，在hackintool里path把平台id变成0x19120000，advance里选也选0x19120000 hd530。不要选0x191B0000

**Comment by CalvinNg-git** [comment]
用hackintool把patch里的Connectors原来index -1 type DP那列的index改成2，type改成HDMI就可以了

**Comment by lyy10** [comment]
那个FX50V有VGA接口，可以支持VGA吗，该怎么修改

**Comment by lyy10** [comment]
> 用hackintool把patch里的Connectors原来index -1 type DP那列的index改成2，type改成HDMI就可以了

请问，你还在用吗，怎么弄好的。可否分享下EFI，邮箱liyunyao1010@163.com.谢谢
